name = "learnadainy"
description = "Learn Ada in Y Minutes"
version = "0.2.0"

authors = ["Luke A. Guest"]
maintainers = ["Luke A. Guest <laguest@archeia.com>"]
maintainers-logins = ["Lucretia"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = "https://learnxinyminutes.com/docs/ada"
tags = ["education"]

executables = ["empty", "hello", "learnadainy"]
